site_name: LORIS
repo_url: https://github.com/aces/Loris
# Solve the broken 404 page issue
site_url: https://loris-dev.readthedocs.io/en/latest/

nav:
    - Home: 'index.md'
    - Wiki: 'wiki/index.md'
    - Server Install and Configuration:
        - 'Prerequisities and Assumptions': 'wiki/00_SERVER_INSTALL_AND_CONFIGURATION/00_Prerequisites_And_Assumptions/README.md'
        - 'Database Configuration': 'wiki/00_SERVER_INSTALL_AND_CONFIGURATION/00_Prerequisites_And_Assumptions/Database_Configuration.md'
        - Installation:
            - 'Ubuntu Install': 'wiki/00_SERVER_INSTALL_AND_CONFIGURATION/01_LORIS_Install/Ubuntu/README.md'
            - 'CentOS Install': 'wiki/00_SERVER_INSTALL_AND_CONFIGURATION/01_LORIS_Install/CentOS/README.md'
        - Website Configuration:
            - 'Website Configuration': 'wiki/00_SERVER_INSTALL_AND_CONFIGURATION/02_Website_Configuration/README.md'
            - 'Handling Large File Uploads': 'wiki/00_SERVER_INSTALL_AND_CONFIGURATION/02_Website_Configuration/Handling_Large_File_Uploads.md'
            - 'Enabling reCAPTCHA': 'wiki/00_SERVER_INSTALL_AND_CONFIGURATION/02_Website_Configuration/reCAPTCHA.md'
    - Study Parameters Setup:
        - Study Variables:
            - Introduction: 'wiki/01_STUDY_PARAMETERS_SETUP/01_Study_Variables/00_Introduction_to_Study_Variables.md'
            - Projects: 'wiki/01_STUDY_PARAMETERS_SETUP/01_Study_Variables/02_Projects.md'
            - Sites: 'wiki/01_STUDY_PARAMETERS_SETUP/01_Study_Variables/03_Sites.md'
            - Subprojects: 'wiki/01_STUDY_PARAMETERS_SETUP/01_Study_Variables/04_Subprojects.md'
            - Timepoints: 'wiki/01_STUDY_PARAMETERS_SETUP/01_Study_Variables/05_Timepoints.md'
        - Clinical Instruments: 'wiki/01_STUDY_PARAMETERS_SETUP/02_Clinical_Instruments/README.md'
        - Modules: 'wiki/01_STUDY_PARAMETERS_SETUP/03_Loris_Modules/README.md'
    - Getting Started: 'wiki/02_GETTING_STARTED/README.md'
    - Help and Troubleshooting: 'wiki/03_HELP_AND_TROUBLESHOOTING/README.md'
    - API: 'API/LorisRESTAPI.md'
    - Developers:
        - Overview: 'wiki/99_Developers/README.md'
        - 'Coding Standards': 'CodingStandards.md'
        - 'SQL Dictionary': 'wiki/99_Developers/SQL_Dictionary.md'
        - 'Automated Testing': 'wiki/99_Developers/Automated_Testing.md'
        - 'Style Guide (for help text)': 'wiki/99_Developers/Help_Style_Guide.md'
        - 'Creating a Module': 'wiki/99_Developers/Creating_Module.md'
        - 'ReactJS Guidelines': 'wiki/99_Developers/ReactJS_Guidelines.md'
        - 'Code Review Guide': 'wiki/99_Developers/Code_Review_Guide.md

use_directory_urls: False

theme:
    name: readthedocs
    custom_dir: 'loris_theme/'
    navigation_depth: 4

plugins:
    - search
    - exclude:
          glob:
            - deprecated_wiki/*
            - wiki/_DELETED/*
            - wiki/_ARCHIVE/*
